# ─────────────────────────────────────────────────────────────────
# VEYDUS — Observability Metrics & Security Counters [SECURITY-CRITICAL]
# ─────────────────────────────────────────────────────────────────
# What:  OpenTelemetry metrics instruments and recording functions defined in HLD §13.2.
# How:   Initializes metric instruments (counters and histograms) for out-of-scope
#        retrieval counts, access filter failures, refusal rates, grounding scores,
#        retrieval rows returned, stage latencies, and token consumption by org.
# Why:   HLD §13.2 mandate: Operational visibility into security invariant breaches
#        (must be 0), filtered-ANN recall collapse (p50 < k), and PRD §8.1 latency budgets.
# Tools: opentelemetry.metrics, opentelemetry.sdk.metrics, uuid.UUID, logging.
# ─────────────────────────────────────────────────────────────────
from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from opentelemetry import metrics

if TYPE_CHECKING:
    from uuid import UUID

    from opentelemetry.metrics import Counter, Histogram

logger = logging.getLogger(__name__)

_meter = metrics.get_meter("veydus", version="0.1.0")

# ── HLD §13.2 Core Metrics Instruments ──────────────────────────
# Security counters (MUST BE 0)
counter_out_of_scope: Counter = _meter.create_counter(
    name="veydus.out_of_scope_retrieval_count",
    description="Number of candidate chunks returned that violate user access scope (must be 0)",
    unit="1",
)

counter_access_filter_failure: Counter = _meter.create_counter(
    name="veydus.access_filter_failure",
    description="Number of critical access filter assertions failed in safety gates (must be 0)",
    unit="1",
)

# Quality metrics
counter_queries_total: Counter = _meter.create_counter(
    name="veydus.queries_total",
    description="Total number of user queries executed",
    unit="1",
)

counter_queries_refused: Counter = _meter.create_counter(
    name="veydus.queries_refused",
    description="Number of queries rejected by grounding or scope gates",
    unit="1",
)

histogram_grounding_score: Histogram = _meter.create_histogram(
    name="veydus.grounding_score",
    description="Distribution of maximum candidate chunk relevance scores",
    unit="1",
)

histogram_retrieval_rows: Histogram = _meter.create_histogram(
    name="veydus.retrieval_rows_returned",
    description="Distribution of chunk counts returned from vector search (detects recall collapse)",
    unit="1",
)

# Performance latency histograms
histogram_auth_and_retrieval_ms: Histogram = _meter.create_histogram(
    name="veydus.latency.auth_and_retrieval_ms",
    description="Auth verification + Scope resolution + Vector search + Reranking latency in ms",
    unit="ms",
)

histogram_ttft_ms: Histogram = _meter.create_histogram(
    name="veydus.latency.ttft_ms",
    description="Time to first generated SSE token from request start in ms",
    unit="ms",
)

# Cost and Operational metrics
counter_prompt_tokens: Counter = _meter.create_counter(
    name="veydus.tokens.prompt",
    description="Total prompt tokens consumed by organization",
    unit="1",
)

counter_completion_tokens: Counter = _meter.create_counter(
    name="veydus.tokens.completion",
    description="Total completion tokens generated by organization",
    unit="1",
)

counter_nim_rate_limited: Counter = _meter.create_counter(
    name="veydus.nim.rate_limited",
    description="Total number of HTTP 429 rate limit responses from inference provider",
    unit="1",
)


def record_out_of_scope_detection(org_id: UUID | str) -> None:
    """Records security invariant breach: candidate chunk violated access scope."""
    logger.critical("ALERT: Out-of-scope candidate chunk detected for org %s!", org_id)
    counter_out_of_scope.add(1, {"org_id": str(org_id)})


def record_access_filter_failure(org_id: UUID | str) -> None:
    """Records security invariant breach: access filter gate rejected chunk."""
    logger.critical("ALERT: Access filter failure triggered for org %s!", org_id)
    counter_access_filter_failure.add(1, {"org_id": str(org_id)})


def record_query_metrics(
    org_id: UUID | str,
    refused: bool,
    grounding_score: float,
    rows_returned: int,
    auth_and_retrieval_ms: float,
    ttft_ms: float,
    prompt_tokens: int = 0,
    completion_tokens: int = 0,
) -> None:
    """Records comprehensive telemetry metrics for a completed or refused query."""
    attrs = {"org_id": str(org_id)}

    counter_queries_total.add(1, attrs)
    if refused:
        counter_queries_refused.add(1, attrs)

    histogram_grounding_score.record(grounding_score, attrs)
    histogram_retrieval_rows.record(rows_returned, attrs)
    histogram_auth_and_retrieval_ms.record(auth_and_retrieval_ms, attrs)
    histogram_ttft_ms.record(ttft_ms, attrs)

    if prompt_tokens > 0:
        counter_prompt_tokens.add(prompt_tokens, attrs)
    if completion_tokens > 0:
        counter_completion_tokens.add(completion_tokens, attrs)


def record_nim_rate_limit(org_id: UUID | str) -> None:
    """Records inference endpoint rate limiting event."""
    counter_nim_rate_limited.add(1, {"org_id": str(org_id)})
